name: ci

on:
  push:
    branches: [main]
    paths-ignore: ['**.md']
  pull_request:
    branches: [main]
    paths-ignore: ['**.md']

jobs:
  ci:
    strategy:
      matrix:
        os: [macos-15, macos-15-intel]

    runs-on: ${{ matrix.os }}
    timeout-minutes: 5

    steps:
    - name: Tap and install
      run: |
        brew tap liquidaty/zsv
        brew install zsv
    
    - name: Check installed version
      run: zsv version

    - name: Uninstall and untap
      run: |
        brew uninstall zsv
        brew untap liquidaty/zsv
        zsv version || true
